# Global Defaults
browser=chrome
env=stage
url=https://superadmin-ui-staging.xrdashboard.com/login
# ExtentReports Theme: 'light' or 'dark' (default: light)
report.theme=light

# Staging Environment
stage.url=https://superadmin-ui-staging.xrdashboard.com/login
stage.username=superadmin@yopmail.com
stage.password=Admin@1234

# Production Environment
prod.url=https://xrdashboard.com/login
prod.username=superadmin@yopmail.com
prod.password=CHANGE_ME

# Default Fallback Credentials
username=superadmin@yopmail.com
password=Admin@1234

# Staging Client Portal Configuration
stage.clientUrl=https://clientportal.xrdashboard.com/login
stage.clientOrgCode=JIL-GJO91P
stage.clientUsername=deepak.s@jcb.com
stage.clientPassword=Shetty@123

# Production Client Portal Configuration
prod.clientUrl=https://client.xrdashboard.com/login
prod.clientOrgCode=CHRP-PTORXJ
prod.clientUsername=mukeshkumar.p@chrp-india.com
prod.clientPassword=Mukesh@123

# Client Portal Configuration (Default / Fallback)
clientUrl=https://clientportal.xrdashboard.com/login
clientOrgCode=JIL-GJO91P
clientUsername=deepak.s@jcb.com
clientPassword=Shetty@123
clientManagerUsername=mahesh.b@jcb.com
clientManagerPassword=Mahesh@123
clientTrainerUsername=mukesh.k@jcb.com
clientTrainerPassword=Mukesh@123