browser=chrome
url=https://superadmin-ui-staging.xrdashboard.com/login
clientUrl=https://clientportal.xrdashboard.com/login
username=superadmin@yopmail.com
password=Admin@1234
clientOrgCode=CHRP
clientUsername=clientadmin@yopmail.com
clientPassword=Client@1234
clientManagerUsername=clientmanager@yopmail.com
clientManagerPassword=Manager@1234
clientTrainerUsername=clienttrainer@yopmail.com
clientTrainerPassword=Trainer@1234